### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by grazaerd** [dnblank123/D-fix#3]
- Low settings
  - [x] Remove player's costume environment reflection
    - Not really visible until you zoom in.
  - [x] Remove shadow on player 
     - Shadow on player only works on Med/High Graphics + High Texture settings (w/o High Texture; shadows will not cast on player's costume/hair).
   - [ ] Remove more texture code 
- High settings
  - [ ] Reduce shadow resolution on player
- Misc
  - [x] Check what is turned on in the settings. (https://github.com/dnblank123/D-fix/commit/7733bc5304e6fdb0c736b8c811fd5a09b716c413)
  - [ ] Refactor on nested if-else statement
  - [ ] Add example changes (before and after)
  - [ ] Tester/Device for Intel GPUs and AMD GPUs
  - [ ] Half-precision floats on shadows(?)
